#pragma once
#include <stdint.h>
#include <stddef.h>

/*
 * serial_writer – drains the ring buffer and writes binary records to UART.
 *
 * A dedicated FreeRTOS task calls serial_writer_task() which loops forever,
 * popping slots and writing them verbatim to the configured UART port.
 *
 * Logs are suppressed via esp_log_set_vprintf(NULL) so UART0 carries only
 * binary records.
 */

void serial_writer_init(void);

/* Entry point for the writer FreeRTOS task – pass NULL as pvParameters. */
void serial_writer_task(void *pvParameters);

/* Write raw bytes directly; used for status records generated by the writer task. */
void serial_writer_send_raw(const void *data, size_t len);
